# Generated by Django 3.2.7 on 2021-09-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210914_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='amount_made',
            field=models.IntegerField(default=0),
        ),
    ]
