# Generated by Django 3.2.7 on 2021-09-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_number_of_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='amount_made',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='number_of_download',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
