# Generated by Django 3.2.7 on 2021-09-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
