# Generated by Django 3.2.7 on 2021-09-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_remove_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
